services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db # Host volume mounted to MongoDB container
    # networks:
    #   - app_network

